export const LANGUAGE_CODE_TO_NAME = {
  af: "Afrikaans",
  ar: "Arabic",
  bg: "Bulgarian",
  bn: "Bengali",
  bs: "Bosnian",
  ca: "Catalan",
  cs: "Czech",
  cy: "Welsh",
  da: "Danish",
  de: "German",
  el: "Greek",
  en: "English",
  eo: "Esperanto",
  es: "Spanish",
  et: "Estonian",
  fi: "Finnish",
  fr: "French",
  gu: "Gujarati",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  hy: "Armenian",
  id: "Indonesian",
  is: "Icelandic",
  it: "Italian",
  ja: "Japanese",
  jw: "Javanese",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  la: "Latin",
  lv: "Latvian",
  mk: "Macedonian",
  ml: "Malayalam",
  mr: "Marathi",
  ms: "Malay",
  my: "Myanmar",
  ne: "Nepali",
  nl: "Dutch",
  no: "Norwegian",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  si: "Sinhala",
  sk: "Slovak",
  sq: "Albanian",
  sr: "Serbian",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tl: "Filipino",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
} as const;

export const SUPPORTED_LANGUAGES = Object.entries(LANGUAGE_CODE_TO_NAME).map(
  ([code, name]) => ({ code, name }),
) as Array<{
  code: keyof typeof LANGUAGE_CODE_TO_NAME;
  name: (typeof LANGUAGE_CODE_TO_NAME)[keyof typeof LANGUAGE_CODE_TO_NAME];
}>;

export type LanguageCode = keyof typeof LANGUAGE_CODE_TO_NAME;
